import Head from 'next/head';

import { Header } from '../components/header/header.component';
import { Hero } from '../components/hero/hero.component';

export default function Home() {
  return (
    <>
      <Head>
        <title>Homepage | Ahoy House</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="language" content="en" />
      </Head>
      <Header type="solid" imageExtend={false} position="sticky" />
      <main>
        <Hero />
      </main>
    </>
  );
}
