// @flow
import * as React from 'react';
import { Formik } from 'formik';
import Head from 'next/head';
import { ToastContainer, toast } from 'react-toastify';
import { GetStaticPaths, GetStaticPropsContext } from 'next';
import * as yup from 'yup';
import { useMutation } from '@apollo/client';
import {  UPDATE_ROOM, fetchRoom, fetchRooms } from '../../../../apollo/room-queries';
import { Room } from '../../../../types/property';
import { AdminNav } from '../../../../components/admin-nav/admin-nav.component';
import { Input } from '../../../../components/input/input.component';
import { Action } from '../../../../components/action/action.component';
import 'react-toastify/dist/ReactToastify.css';

type Props = {
  room: Room;
};

export const getStaticProps = async ({ params }: GetStaticPropsContext<{ slug: string }>) => {
  console.log(params?.slug);
  const data = params?.slug ? await fetchRoom(params?.slug) : '';
  return {
    props: {
      room: data ? data.getRoom : [],
    },
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  const rooms: Room[] = await fetchRooms();
  console.log(rooms);
  const paths = rooms.map((room) => {
    return {
      params: {
        slug: room.id,
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

const validationSchema = yup.object().shape({
  name: yup.string().required('Name of the property is required'),
  description: yup.string().required('Description is required'),
  capacity: yup.number().required('Number of bathrooms is required'),
  livingArea: yup.number().required('Size is required'),
  pricePerNight: yup.number().required('Price per night is required'),
  propertyId: yup.string().required('Property ID code is required'),
  amenities: yup.string().required('Amenities are required'),
});

const EditRoom = ({ room }: Props) => {
  const [updateRoom] = useMutation(UPDATE_ROOM);
  const initialValue = {
    description: room.description,
    pricePerNight: room.pricePerNight,
    capacity: room.capacity,
    name: room.name,
    livingArea: room.livingArea,
    propertyId: room.propertyId,
    amenities: room.amenities,
  };

  const submitForm = async (values: typeof initialValue) => {
    console.log(values);

    const { data } = await updateRoom({
      variables: {
        description: values.description,
        pricePerNight: values.pricePerNight,
        capacity: values.capacity,
        name: values.name,
        livingArea: values.livingArea,
        propertyId: values.propertyId,
        amenities: values.amenities,
        id: room.id,
      },
    });
    return data;
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AdminNav />
      <ToastContainer style={{ fontSize: '1.6rem' }} pauseOnHover hideProgressBar />
      <main className='page '>
        <ToastContainer style={{ fontSize: '1.6rem' }} pauseOnHover hideProgressBar />
        <div className='row'>
          <h1 className='heading'>Add Property</h1>

          <Formik
            initialValues={initialValue}
            validationSchema={validationSchema}
            onSubmit={async (values, actions) => {
              try {
                console.log(values);

                console.log(await submitForm(values));
                toast.success('Form submitted');
                // actions.resetForm();
              } catch (error) {
                console.log(values);
                toast.error('Submission failed');
                // actions.resetForm();
              }
            }}
          >
            {({ values, handleSubmit, handleChange, isSubmitting, dirty, isValid, errors, ...props }) => {
              return (
                <>
                  <form onSubmit={handleSubmit}>
                    <Input
                      onChange={handleChange}
                      value={values.name}
                      required
                      name='name'
                      label='Property Name'
                      placeholder='e.g. Silver House'
                    />
                    <Input
                      onChange={handleChange}
                      value={values.description}
                      required
                      name='description'
                      type='textarea'
                      label='Description'
                      placeholder='Describe the property'
                    />
                    <Input
                      onChange={handleChange}
                      value={values.capacity}
                      required
                      name='capacity'
                      type='number'
                      label='Capacity number of guests'
                      placeholder='e.g. 1'
                    />
                    <Input
                      onChange={handleChange}
                      value={values.livingArea}
                      required
                      name='livingArea'
                      type='number'
                      label='Living Area (sqft) '
                      placeholder='e.g. 981'
                    />
                    <Input
                      onChange={handleChange}
                      value={values.pricePerNight}
                      required
                      name='pricePerNight'
                      label='Price Per Night'
                      placeholder='e.g. $50'
                    />
                    <Input
                      onChange={handleChange}
                      value={values.amenities}
                      required
                      name='amenities'
                      label='Amenities'
                      placeholder='e.g. Fridge, Wi-Fi, Free Parking'
                    />
                    <Input
                      onChange={handleChange}
                      value={values.propertyId}
                      required
                      name='propertyId'
                      label='Property ID'
                      placeholder='e.g. lkusdf-21312-asdasd'
                    />
                    <Action disabled={!isValid || !dirty} as='button' type='submit' styleType='primary'>
                      Submit
                    </Action>
                  </form>
                </>
              );
            }}
          </Formik>
        </div>
      </main>
    </>
  );
};

export default EditRoom;
