version: '3.3'
services:
  postgres:
    image: "postgres:14.5"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ahoy-house-dev
    ports:
      - "5432:5432"
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
