// @flow
import * as React from 'react';
import { Header } from '../../components/header/header.component';
import Head from 'next/head';
import { AdminNav } from '../../components/admin-nav/admin-nav.component';
type Props = {};
const AdminDashboard = (props: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AdminNav />
      <main className='page '>
        <div className='row'>
            <h1 className='heading'>Admin Dashboard</h1>
        </div>
      </main>
    </>
  );
};

export default AdminDashboard;
