// @flow
import * as React from 'react';
import { Property } from '../../types/property';
import { PROPERTY_DATA } from '../../mock/property.data';
import { GetStaticPaths, GetStaticProps, GetStaticPropsContext } from 'next';
import { Header } from '../../components/header/header.component';
import Head from 'next/head';
import { PropertyGallery } from '../../components/property-gallery/property-gallery.components';
import { PropertyImageCarousel } from '../../components/property-card/property-image-carousel.component';
import { PropertyCalculation } from '../../components/property-calculation/property-calculation.component';
import { apolloClient } from '../../utils/apollo-client';
import { gql } from '@apollo/client';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { fetchActiveProperties, fetchActiveProperty } from '../../apollo/property-queries';

type Props = {
  property: Property;
};

export const getStaticProps = async ({ params }: GetStaticPropsContext<{ slug: string }>) => {
  const data = params?.slug ? await fetchActiveProperty(params?.slug) : '';
  return {
    props: {
      property: data ? data.getActiveProperty : [],
    },
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  const properties: Property[] = await fetchActiveProperties();
  const paths = properties.map((property) => {
    return {
      params: {
        slug: property.id,
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

const PropertyDetail = ({ property }: Props) => {
  return (
    <>
      <Head>
        <title>{`${property.name} | Ahoy House`}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header imageExtend={true} type='solid' position='sticky' />
      <ToastContainer style={{ fontSize: '1.6rem' }} pauseOnHover hideProgressBar />
      <main>
        <div className='row'>
          <h1 className='heading'>{property.name}</h1>
          <div className='row-2-1'>
            <div className='property-gallery'>
              <PropertyImageCarousel imageData={property.images} width='76rem' height='46.4rem' />
            </div>
            <PropertyCalculation property={property} />
          </div>
        </div>
      </main>
    </>
  );
};

export default PropertyDetail;
