// @flow
import * as React from 'react';
import { Property } from '../../types/property';
import { PROPERTY_DATA } from '../../mock/property.data';
import { GetStaticPaths, GetStaticProps, GetStaticPropsContext } from 'next';
import { Header } from '../../components/header/header.component';
import Head from 'next/head';
import { PropertyGallery } from '../../components/property-gallery/property-gallery.components';
import { PropertyImageCarousel } from '../../components/property-card/property-image-carousel.component';
import { PropertyCalculation } from '../../components/property-calculation/property-calculation.component';
import {apolloClient} from '../../utils/apollo-client';
import { gql } from '@apollo/client';

type Props = {
  property: Property;
};

const fetchProperty = async (id: string) => {
  const { data } = await apolloClient.query({
    query: gql`
      query getActiveProperty($id: String!) {
        getActiveProperty(id: $id) {
          id
          description
          numberRooms
          numberBaths
          livingArea
          address
          postalCode
          name
          rooms {
            id
            description
            name
            livingArea
            pricePerNight
          }
        }
      }
    `,
    variables: {
      id: id,
    },
  });
  return data;
};
const fetchProperties = async () => {
  const { data } = await apolloClient.query({
    query: gql`
      query getAllActiveProperties {
        getAllActiveProperties {
          id
          description
          numberRooms
          numberBaths
          livingArea
          address
          postalCode
          name
          rooms {
            id
            description
            name
            livingArea
            pricePerNight
          }
        }
      }
    `,
  });
  return data.getAllActiveProperties;
};

// export const getStaticProps = ({ params }: GetStaticPropsContext<{ slug: string }>) => {
//   const properties = PROPERTY_DATA;
//   const findPropertyById = properties.find((property) => {
//     return property.id.toString() === params?.slug; //dynamic id
//   });
//   return {
//     props: {
//       property: findPropertyById ? findPropertyById : [],
//     },
//   };
// };

export const getStaticProps = async ({ params }: GetStaticPropsContext<{ slug: string }>) => {
  const data = params?.slug ? await fetchProperty(params?.slug) : '';
  return {
    props: {
      property: data ? data.getActiveProperty : [],
    },
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  const properties: Property[] = await fetchProperties();
  const paths = properties.map((property) => {
    return {
      params: {
        slug: property.id,
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

const PropertyDetail = ({ property }: Props) => {
  console.log(property);
  return (
    <>
      <Head>
        <title>{`${property.name} | Ahoy House`}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header imageExtend={true} type='solid' position='sticky' />
      <main>
        <div className='row'>
          <h1 className='heading'>{property.name}</h1>
          <div className='row-2-1'>
            <div className='property-gallery'>
              <PropertyImageCarousel imageData={PROPERTY_DATA[0].images} width='76rem' height='46.4rem' />
            </div>
            <PropertyCalculation property={property} />
          </div>
        </div>
      </main>
    </>
  );
};

export default PropertyDetail;
