import Head from 'next/head';
import { Header } from '../../components/header/header.component';
import { PropertyCard } from '../../components/property-card/property-card.component';
import { gql } from '@apollo/client';
import { apolloClient } from '../../utils/apollo-client';
import { Property } from '../../types/property';
import { GetServerSideProps, GetStaticProps } from 'next';
import { GET_ACTIVE_PROPERTIES } from '../../apollo/property-queries';

interface Props {
  properties: Property[];
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const { data } = await apolloClient.query({
    query: GET_ACTIVE_PROPERTIES,
  });

  return {
    props: {
      properties: data.getAllActiveProperties,
    },
  };
};

export default function Properties({ properties, ...props }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header imageExtend={true} type='solid' position='sticky' />
      <main>
        <div className='row page'>
          <h2 className='heading'>Our Properties</h2>

          <section className='properties-grid'>
            {properties.map((property, index) => (
              <PropertyCard key={index} property={property} index={index}/>
            ))}
          </section>
        </div>
      </main>
    </>
  );
}
