import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../../styles/Home.module.css';
import Link from 'next/link';
import { Header } from '../../components/header/header.component';
import { Action } from '../../components/action/action.component';
import { Button } from '../../components/button/button.component';
import { FeatureCard } from '../../components/feature-card/feature-card.component';
import { PropertyCard } from '../../components/property-card/property-card.component';

const inter = Inter({ subsets: ['latin'] });

export default function Properties() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className='card' style={{ margin: '10px' }}>
          <div className='display--large--bold'>Display Text Large BoldThe quick</div>
          <div className='display--large'>Display Text Large Semibold</div>
          <div className='display--large--medium'>Display Text Large Medium</div>
          <div className='display--small--bold'>Display Text Bold</div>
          <div className='display--small'>Display Text Small Semibold</div>
          <div className='display--small--medium'>Display Text Medium</div>
        </div>
        <div className='card' style={{ margin: '10px' }}>
          <h1 className='heading--bold'>Heading 1 Bold</h1>
          <h1 className='heading'>Heading 1</h1>
          <h1 className='heading--medium'>Heading 1 Medium</h1>
          <h2 className='heading--bold'>Heading 2 Bold</h2>
          <h2 className='heading'>Heading 2</h2>
          <h2 className='heading--medium'>Heading 2 Medium</h2>
          <h3 className='heading--bold'>Heading 3 Bold</h3>
          <h3 className='heading'>Heading 3</h3>
          <h3 className='heading--medium'>Heading 3 Medium</h3>
          <h4 className='heading--bold'>Heading 4 Bold</h4>
          <h4 className='heading'>Heading 4</h4>
          <h4 className='heading--medium'>Heading 4 Medium</h4>
          <h5 className='heading--bold'>Heading 5 Bold</h5>
          <h5 className='heading'>Heading 5</h5>
          <h5 className='heading--medium'>Heading 5 Medium</h5>
          <h6 className='heading--bold'>Heading 6 Bold</h6>
          <h6 className='heading'>Heading 6</h6>
          <h6 className='heading--medium'>Heading 6 Medium</h6>
        </div>
        <div className='card' style={{ margin: '10px' }}>
          <p className='paragraph--large--bold'>Body Text Large Bold</p>
          <p className='paragraph--large'>Body Text Large</p>
          <p className='paragraph--medium--bold'>Body Text Medium Bold</p>
          <p className='paragraph--medium'>Body Text Medium</p>
          <p className='paragraph--small--bold'>Body Text Small Bold</p>
          <p className='paragraph--small'>Body Text Small</p>
        </div>
        <div className='card' style={{ margin: '10px' }}>
          <div className='caption--large--bold'>Caption Text Large Bold</div>
          <div className='caption--large'>Caption Text Large</div>
          <div className='caption--medium--bold'>Caption Text Medium Bold</div>
          <div className='caption--medium'>Caption Text Medium</div>
        </div>

        <Header />
        <div className='card' style={{ margin: '10px', backgroundColor: '#8b8b8b' }}>
          <Action as='button' styleType='primary'>
            Primary
          </Action>
          <Action as='link' href='#!' styleType='secondary'>
            Primary
          </Action>
          <Button role='button' className='outline'>
            Primary
          </Button>
          <Link href='/' className='btn--link'>
            Primary
          </Link>
        </div>
        <div className='card' style={{ margin: '10px', display:"flex", gap:"2.4rem" }}>
          <FeatureCard
            description='Highly professional standards ensure sleep quality and cleanliness.'
            title='Boutique experience in a private room'
            imgUrl='/static/illustrations/bed.jpg'
            alt='Cafe meeting'
          />
          <FeatureCard
            description='Fully furnished a student room in each house and dedicated from the rush part.'
            title='Study places in all houses'
            imgUrl='/static/illustrations/cafe.jpg'
            alt='Cafe meeting'
          />
          <FeatureCard
            description='Meeting rooms used for business occasions or formal negotiations.'
            title='Spaces for business meetings'
            imgUrl='/static/illustrations/meeting-room.jpg'
            alt='Cafe meeting'
          />
        </div>
      <div className='card' style={{ margin: '10px', display:"flex", gap:"2.4rem" }}>
        <PropertyCard/>
      </div>
      </main>
    </>
  );
}
